#pragma once

namespace strokes::ui {

// Control identifiers shared by the settings window and its editors. IDOK and
// IDCANCEL are reserved by the dialog manager and are mapped onto save_id and
// cancel_id by the window's command handler.
enum : int {
  settings_section_label_id = 90,
  advanced_section_label_id,
  activation_label_id,
  overlay_width_label_id,
  overlay_opacity_label_id,
  movement_label_id,
  distance_label_id,
  maximum_label_id,
  recognition_label_id,
  enabled_id = 101,
  button_id,
  move_id,
  distance_id,
  max_id,
  threshold_id,
  overlay_id,
  width_id,
  opacity_id,
  editor_tabs_id,
  gesture_inventory_id,
  gesture_section_label_id,
  global_action_label_id,
  assigned_action_label_id,
  gesture_preview_id,
  gesture_select_id,
  shortcut_id,
  gestures_id,
  gesture_name_id,
  gesture_add_id,
  gesture_rename_id,
  gesture_delete_id,
  gesture_train_id,
  gesture_remove_sample_id,
  gesture_toggle_id,
  profile_section_label_id,
  profile_name_label_id,
  profile_property_label_id,
  profile_mode_label_id,
  profile_value_label_id,
  profile_override_label_id,
  profile_criteria_label_id,
  profiles_id,
  profile_name_id,
  profile_property_id,
  profile_mode_id,
  profile_value_id,
  profile_criteria_id,
  criterion_add_id,
  criterion_update_id,
  criterion_remove_id,
  profile_shortcut_id,
  profile_add_id,
  profile_update_id,
  profile_delete_id,
  profile_toggle_id,
  profile_assign_id,
  global_assign_id,
  global_remove_id,
  help_text_id,
  save_id,
  cancel_id
};

}  // namespace strokes::ui
